name:                menshen
version:             0.0.4
synopsis:            Data Validation
description:         Data Validation inspired by JSR305
homepage:            https://github.com/leptonyu/menshen#readme
license:             BSD3
author:              Daniel YU
maintainer:          leptonyu@gmail.com
copyright:           (c) Daniel YU
category:            Web
extra-source-files:
- README.md

ghc-options: -Wall -fno-warn-orphans -fno-warn-missing-signatures

dependencies:
  - base >= 4.7 && < 5
  - text
  - scientific
  - regex-tdfa
  - regex-tdfa-text
  - exceptions

library:
  source-dirs: src
  exposed-modules:
    - Data.Menshen

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - menshen
      - aeson
